In [ ]:
conda install numpy

In [1]:
import numpy as np
np.__version__

'1.19.2'

In [2]:
a=np.array([1,2,3,4,5])

In [3]:
a

array([1, 2, 3, 4, 5])

In [4]:
type(a)

numpy.ndarray

In [6]:
b=np.linspace(0,20,num=21,endpoint=True)
print(b)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20.]


In [11]:
c=b[2::2]
print(c)

[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]


In [12]:
d=b[3::3]
print(d)

[ 3.  6.  9. 12. 15. 18.]
