In [1]:
import numpy as np

In [3]:
array1 = np.array([[10, 8], [3, 5]])

1.
a=np.linalg.inv(array1)
a

array([[ 0.19230769, -0.30769231],
       [-0.11538462,  0.38461538]])

In [5]:
np.dot(array1,a)

array([[ 1.00000000e+00,  0.00000000e+00],
       [-1.38777878e-17,  1.00000000e+00]])

In [6]:
2.
eigenvalue,eigenvector=np.linalg.eig(array1)

In [7]:
eigenvalue

array([13.,  2.])

In [8]:
eigenvector

array([[ 0.93632918, -0.70710678],
       [ 0.35112344,  0.70710678]])

In [9]:
3.
np.linalg.matrix_rank(array1)

2